try alternative exponential backoff implementation

diff --git a/roles/StackStorm.st2smoketests/tasks/st2chatops.yml b/roles/StackStorm.st2smoketests/tasks/st2chatops.yml
--- a/roles/StackStorm.st2smoketests/tasks/st2chatops.yml
+++ b/roles/StackStorm.st2smoketests/tasks/st2chatops.yml
@@ -1,7 +1,13 @@
 ---
 - name: Verify st2chatops using bin/hubot
   # when editing, make sure it works for at least 2 adapters: 'shell' and 'slack'
-  shell: "set -o pipefail && timeout {{ hubot_timeout }} bash -c '(sleep {{ hubot_sleep }}; echo exit ) | bin/hubot'"
+  shell: >
+    set -o pipefail &&
+    export a=/tmp/.hubot.{{ 10000 | random }}.attempts &&
+    export n=$(cat $a 2>/dev/null || echo 0) &&
+    timeout $(( 9 + 5 ** n )) bash -c '(sleep $(( 4 + 5 ** n )); echo exit ) | bin/hubot' &&
+    echo $((n+1)) > $a
+  # $a,$n = homegrown exponential backoff (increasing sleep lets the slack client lib retry automatically)
   args:
     chdir: /opt/stackstorm/chatops/
     executable: /bin/bash
@@ -17,11 +23,7 @@
   until: "'Rate limited, will retry' not in hubot_output.stdout_lines | last"
   retries: 3
   # random delay so that retries accross parallel runs don't perfectly align
-  delay: "{{ 15 + lookup('random_choice', *range(7)) }}"
-  vars:
-    # homegrown exponential backoff (allows the slack client lib to retry automatically)
-    hubot_sleep: "{{ 5 + 5 ** (hubot_output | default({'attempts': 0})).attempts }}"
-    hubot_timeout: "{{ (hubot_sleep | int) + 5 }}"
+  delay: "{{ 15 + (7 | random) }}"
 
 # Additional task to provide better error message
 - name: Fail if st2chatops couldn't load st2 commands
